### ISSUE TITLE
Trial period has expired

### ISSUE THREAD

**Issue by tonykoval** [flexmonster/pivot-kibana#1]
I was trying to run kibana plugin, but I got error:

Your trial period has expired.
Read more info about this error
You are trying to use the following key: Z7AB-XB421G-6H4G5S-1R0I46

Any idea?

**Comment by flexmonster** [comment]
Hi Tony!
Please try to run _yarn upgrade_ in the plugin's folder. This should help.
Thanks

**Comment by tonykoval** [comment]
It didn't help, same error. I tried also remove folder node_modules.
![pivot](https://user-images.githubusercontent.com/1135652/61375686-c9c66680-a89f-11e9-8784-8fa966948424.png)

**Comment by tonykoval** [comment]
After reloading the newest version the flexmonster, it works :)
