### ISSUE TITLE
How do you set the license key?

### ISSUE THREAD

**Issue by cruikshj** [flexmonster/pivot-kibana#11]
How do you set the licenseKey for flexmonster when using this Kibana plugin?

I see how you can do it when embedding the chart normally in javascript... but not with kibana.

Thanks!

**Comment by iansadovy** [comment]
Hello @cruikshj ,

Thank you for writing.
Currently, you can use Flexmonster Kibana plugin with a trial license key, or set `licenseKey` by modifying the the plugin's code.

https://github.com/flexmonster/pivot-kibana/blob/41ee1fa1c082fd47e991c5a339898934d0d559f8/public/components/flexmonster/FlexmonsterPivotTable.js#L40-L42

In the future, we are going to add an ability to configure the license key in the kibana.yml or via UI.

Hope it helps.

Regards,
Ian
