### ISSUE TITLE
Plugin is available but Pivot Table is missing

### ISSUE THREAD

**Issue by amikulichregtek** [flexmonster/pivot-kibana#16]
When I switch to flexmonster_pivot plugin tab I see only empty page, no any table available

flexmonster_pivot
Use kibana and elastic with version  7.4.1. and plugin version 1.2.3

When I look into page sources i see a code 

`<div class="kibanaWelcomeView" id="kbn_loading_message" style="display: none;">
            <div class="kibanaLoaderWrap">
                <div class="kibanaLoader"></div>
                <div class="kibanaWelcomeLogoCircle">
                    <div class="kibanaWelcomeLogo"></div>
                </div>
            </div>
            <div class="kibanaWelcomeText" data-error-message="Kibana did not load properly. Check the server output for more information.">Loading Kibana</div>
        </div>
        <div class="kibanaWelcomeView" id="kbn_legacy_browser_error" style="display: none;">
            <div class="kibanaLoaderWrap">
                <div class="kibanaWelcomeLogoCircle">
                    <div class="kibanaWelcomeLogo"></div>
                </div>
            </div>
            <h2 class="kibanaWelcomeTitle">Please upgrade your browser</h2>
            <div class="kibanaWelcomeText">This Kibana installation has strict security requirements enabled that your current browser does not meet.</div>
        </div>`

Use mac os Hight Siera 10.13.6 and Chrome Version 78.0.3904.108

**Comment by tsshn** [comment]
Hello,

Thank you for reaching out to us.

Please, consider that release 1.21 of the plugin works with Kibana 7.3.2.

As for the Kibana 7.4.1, it seems that they made some breaking changes, and now the plugin does not work. Currently, we recommend making changes in the source code of the plugin to support the latest version of Kibana or using it with Kibana 7.3.2. For the latest versions, please make changes in the package.json and/or other files if necessary.

Feel free to contact us in case of additional questions occur.

Kind Regards,
Illia
