### ISSUE TITLE
install the plug error

### ISSUE THREAD

**Issue by fish-gangan** [flexmonster/pivot-kibana#5]
bin/kibana-plugin install https://github.com/flexmonster/pivot-kibana/releases/download/v1.15/flexmonster_pivot-v1.15.zip
Attempting to transfer from https://github.com/flexmonster/pivot-kibana/releases/download/v1.15/flexmonster_pivot-v1.15.zip
Transferring 10549 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "EACCES: permission denied, open '/soft/kibana/kibana-7.2.0-linux-x86_64/plugins/.plugin.installing/package.json'"

(I use the user kibana created by myself,and the version of my kibana is 7.2.)

**Comment by tzachshabtay** [comment]
Are you installing from a docker image?
If so, you need to use a root user for it (i.e if you're using docker-compose you can add `user: root`) and also add a `--allow-root` to the `kibana-plugin install` command.

**Comment by Uaman** [comment]
Such an issue means that there is an issue with permissions.
You will need to run `kibana-plugin install --allow-root ...` command with `sudo`. In other case, you can still face that error.

**Comment by fish-gangan** [comment]
> Are you installing from a docker image?
> If so, you need to use a root user for it (i.e if you're using docker-compose you can add `user: root`) and also add a `--allow-root` to the `kibana-plugin install` command.

**Comment by fish-gangan** [comment]
> Are you installing from a docker image?
> If so, you need to use a root user for it (i.e if you're using docker-compose you can add `user: root`) and also add a `--allow-root` to the `kibana-plugin install` command.

I haven't  used docker  but this still take effect,thanks.

**Comment by fish-gangan** [comment]
> Such an issue means that there is an issue with permissions.
> You will need to run `kibana-plugin install --allow-root ...` command with `sudo`. In other case, you can still face that error.

bin/kibana-plugin --allow-root  install https://github.com/flexmonster/pivot-kibana/releases/download/v1.15/flexmonster_pivot-v1.15.zip    
thank you,i success with --allow-root

**Comment by ebuildy** [comment]
Here what I did with official Docker image:

```
FROM docker.elastic.co/kibana/kibana:7.3.2

USER root

RUN bin/kibana-plugin install --allow-root https://github.com/flexmonster/pivot-kibana/releases/download/v1.21/flexmonster_pivot-v1.21.zip

RUN cd plugins/flexmonster_pivot && \
    PATH=$PATH:/usr/share/kibana/node/bin:/usr/share/kibana/node_modules/yarn/bin \
    yarn upgrade

USER kibana
```
