### ISSUE TITLE
 kibana   fail to load 

### ISSUE THREAD

**Issue by fish-gangan** [flexmonster/pivot-kibana#7]
when i restart my kibana,something happened,but not the manifest error!  logs showing
` log   [02:49:03.926] [warning][plugin] Skipping non-plugin directory at /soft/kibana/kibana-7.2.0-linux-x86_64/plugins/flexmonster_pivot
`
and i can't find the button of flemonster on the kibana board

![image](https://user-images.githubusercontent.com/33407933/62508047-dc95e080-b838-11e9-8f37-66e293344c68.png)

**Comment by Venkat477** [comment]
Any update on this...I'm also facing the same issue

**Comment by iansadovy** [comment]
Hello @fish-gangan ,

Please try to deploy kibana as root
```
sudo su
./kibana –allow-root
```

Details are here: https://www.flexmonster.com/question/unable-to-install-flexmonster-pivot-plugin-in-kibana/

Hope it helps.
