### ISSUE TITLE
Configurable elasticsearch host

### ISSUE THREAD

**Issue by tzachshabtay** [flexmonster/pivot-kibana#8]
The elasticsearch host url is currently hard-coded to localhost:
https://github.com/flexmonster/pivot-kibana/blob/5876f8f3eb39af35469a6eabc9154502adb0a9f3/public/app.js#L13

Please make it configurable, thanks.

**Comment by tzachshabtay** [comment]
Hi, I tested your latest release which "fixes hard-coded localhost", it doesn't work.

If I understand correctly, you're taking the url for elasticsearch directly from kibana. This is cool, but the problem with that is that you're making the requests to elasticsearch from the client and not from the server.
You're assuming they're on the same network but it's not always the case (it's not the case for us).
Elastic is not publicly exposed with the same url that's used in kibana (we do publicly expose elasticsearch via our load balancer using a different url, but I imagine that for other users elasticsearch might not be publicly exposed at all).

The solution should be to make the requests to elasticsearch from the kibana server, not the client, then it will work.

**Comment by iansadovy** [comment]
Hello @tzachshabtay ,

Thank you for the feedback.
It sounds reasonable. But currently, Flexmonster Pivot Table supports only direct connection to Elasticsearch. So, we need to implement additional functionality to make it work with Kibana as a proxy between Flexmonster and ES. It may take some time.

We will keep you updated on this matter.

Regards,
Ian

**Comment by shobhitsinghal624** [comment]
+1 for this. We also do not have elasticsearch publicly available.

**Comment by mhalaida** [comment]
Hi @shobhitsinghal624,

Thank you for your feedback here.

As of right now, there are no updates on this matter and only direct connection to Elasticsearch is supported by Flexmonster Pivot Table. We will make sure to inform you if we have any news regarding this topic.

Best regards,
Mykhailo

**Comment by ebuildy** [comment]
You should not call elasticsearch API from Javascript !

Also, the Kibana ``elasticsearc.host`` setting is for communication between Kibana **SERVER** and elasticsearch, not Kibana Javascript.

You should create a ``server`` part that will do the communication with elasticsearch.

**Comment by VeraDidenko** [comment]
Hello, @ebuildy,

Yes, this is a known issue that was mentioned earlier in this thread by @tzachshabtay.

 

Nevertheless, thank you for sharing your thoughts with us. 

Our team has taken these points into consideration.

 

We will keep you updated.

 

Kind regards,
Vera
