### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by tzachshabtay** [flexmonster/pivot-kibana#9]
The flexmonster website shows that you support "live data", but from what I've seen it appears that the kibana wrapper doesn't support it?
I.e we would like to have the on/off toggle for auto-refresh that all the other kibana tabs (Discover, visualizations, dashboards) have.

Thanks.

**Comment by iansadovy** [comment]
Thank you for the feedback.

We will add this feature request to our backlog.
Just for the reference, with Flemonster API it's done via [updateData](https://www.flexmonster.com/api/updatedata/) method.

Regards,
Ian
